### ISSUE TITLE
How's progress going?

### ISSUE THREAD

**Issue by Danielvandervelden** [KillerInk/TT2Clicker#3]
Yo man,

Was just wondering how progress is coming along. Any ETA on a proper release yet?

Thanks for the hard work!

**Comment by KillerInk** [comment]
Its a slow progress. Having problems with scene transition.
Also sometimes random touches happen, where im not sure if caused by memu or just tt2 touchevent implementation is bad, but i tend to say its tt2. It runs now for12 hours without a problem from above. So my changes seem to work.
In meantime i added skill unlock and level. But its a wip. Need more patches from the font they use for the skill lvls.
I dont know wich problems will appear next, cant say much about a proper release.

**Comment by Danielvandervelden** [comment]
Aight sounds good already though. Thanks for the update!

**Comment by KillerInk** [comment]
yeah next problem appeared.
scene transitions detector works to good. 
it blocks now all taps also when you collect a pet or weapon, wich is the correct behavior on a scene transition

**Comment by KillerInk** [comment]
preview2 is out.
only thing now is left CQs and fixing bugs that appear

prestige timer seems buggy and seems it gets ignored, prestige trigger only after xxx bossfight fails

**Comment by jepistons** [comment]
for some reason the bot is not working for me

**Comment by KillerInk** [comment]
What happen? Sure you using memu < 6.0.1 and granted the screenrecorder permission?
